DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json


{
    "name": "Stan Lee", 
    "phone" : "0121 435 46732"
}


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Hello world", 
    "phone" : "0121 435 46732"
}


###
#testing error for no number
POST http://localhost:3001/api/persons
Content-Type: application/json


{
    "name": "Stan Lee"
}

###
#testing no name
POST http://localhost:3001/api/persons
Content-Type: application/json


{
    "phone" : "0121 435 46732"
}


###
#testing duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json


{
    "name": "Max power", 
    "phone" : "0121 435 46732"
}


###
#testing the backend

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test Name", 
    "phone" : "9090909090"
}

###
#testing put request
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{
    "name" : "Ishaq", 
    "phone" : "07786954332"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lol0000",
    "phone" : "09090909099090"
}