GET http://localhost:3001/api/notes 

###

POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Will this load up?", 
    "important" : true
}

###

PUT  http://localhost:3001/api/notes/1
Content-Type: application/json

{
    "content" : "Updated note", 
    "important" : true
}